services:
  # ===== Database / Infra =====
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
      POSTGRES_DB: appdb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  mongo:
    image: mongo:7
    ports:
      - "27017:27017"
    volumes:
      - mongodata:/data/db

  redis:
    image: redis:7
    ports:
      - "6379:6379"

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"

  # ===== API Gateway =====
  gateway:
    build: ./services/gateway
    ports:
      - "8080:8080"
    environment:
      JWT_SECRET: supersecret
      AUTH_URL: http://auth-service:3001
      PRICING_URL: http://pricing-service:3002
      RIDE_URL: http://ride-service:3003
      PAYMENT_URL: http://payment-service:3004
    depends_on:
      - auth-service
      - pricing-service
      - ride-service
      - payment-service

  # ===== Core services =====
  auth-service:
    build: ./services/auth-service
    environment:
      JWT_SECRET: supersecret
      MONGO_URL: mongodb://mongo:27017/authdb
    depends_on:
      - mongo

  pricing-service:
    build: ./services/pricing-service
    ports:
      - "3002:3002"

  ride-service:
    build: ./services/ride-service
    environment:
      PG_URL: postgres://app:app@postgres:5432/appdb
      REDIS_URL: redis://redis:6379
      RABBIT_URL: amqp://guest:guest@rabbitmq:5672
    depends_on:
      - postgres
      - redis
      - rabbitmq

  payment-service:
    build: ./services/payment-service
    environment:
      RABBIT_URL: amqp://guest:guest@rabbitmq:5672
    depends_on:
      - rabbitmq

  notification-service:
    build: ./services/notification-service
    environment:
      RABBIT_URL: amqp://guest:guest@rabbitmq:5672
      REDIS_URL: redis://redis:6379
    depends_on:
      - rabbitmq
      - redis

volumes:
  pgdata:
  mongodata:
